# -*- coding: utf-8 -*-
"""
Created on Sat Mar 11 21:23:17 2023

Dictionary to translate opta event types from numeric to character

@author: adamm
"""

optaEventTypes = {
    1:'Pass',
    2:'Offside Pass',
    3:'Take On',
    4:'Foul',
    5:'Out',
    6:'Corner Awarded',
    7:'Tackle',
    8:'Interception',
    10:'Save',
    11:'Claim',
    12:'Clearance',
    13:'Miss',
    14:'Post',
    15:'Attempt Saved',
    16:'Goal',
    17:'Card',
    18:'Player Off',
    19:'Player On',
    20:'Player retired',
    21:'Player returns',
    22:'Player becomes goalkeeper',
    23:'Goalkeeper becomes player',
    24:'Condition change',
    25:'Official change',
    27:'Start delay',
    28:'End delay',
    30:'End',
    32:'Start',
    34:'Team set up',
    35:'Player changed positon',
    36:'Player changed Jersey',
    37:'Collection End',
    38:'Temp_Goal',
    39:'Temp_attempt',
    40:'Formation change',
    41:'Punch',
    42:'Good skill',
    43:'Deleted event',
    44:'Aerial',
    45:'Challenge',
    49:'Ball recoevery',
    50:'Dispossessed',
    51:'Error',
    52:'Keeper pick-up',
    53:'Cross not claimed',
    54:'Smoother',
    55:'Offside provoked',
    56:'Shield ball opp',
    57:'Foul throw-in',
    58:'Penalty faced',
    59:'Keeper sweeper',
    60:'Chance missed',
    61:'Ball touch',
    63:'Temp_Save',
    64:'Resume',
    65:'Contentious referee decision',
    67:'50/50',
    68:'Referee Drop Ball',
    70:'Injury time announcement',
    71:'Coach Setup',
    74:'Blocked Pass',
    75:'Delayed Start',
    76:'Early end',
    79:'Coverage interruption',
    80:'Drop of ball',
    81:'Obstacle',
    82:'Control',
    83:'Attempted Tackle',
    84:'Deleted After Review'}
